In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Covid.csv")

In [4]:
df.head(10)

,gender,age_year,fever,cough,runny_nose,muscle_soreness,pneumonia,diarrhea,lung_infection,travel_history,isolation_treatment,SARS-CoV-2 Positive
0,male,89,1,1,0,0,0,0,0,1,0,0
1,male,68,1,0,0,0,0,0,0,0,0,0
2,male,68,0,0,0,0,0,0,0,1,0,0
3,male,68,1,1,0,0,0,0,0,1,1,1
4,male,50,1,1,1,0,1,0,0,1,0,1
5,male,50,1,1,0,0,0,0,0,0,0,1
6,female,55,1,1,0,0,0,0,0,0,0,0
7,female,55,0,0,0,0,0,0,0,1,0,0
8,female,55,1,1,0,0,0,0,0,0,0,1
9,female,48,1,1,0,0,0,0,0,1,0,0

In [5]:
from matplotlib import pyplot as plt
import seaborn as sns
import math

In [6]:
df.isna().sum()

gender                 0
age_year               0
fever                  0
cough                  0
runny_nose             0
muscle_soreness        0
pneumonia              0
diarrhea               0
lung_infection         0
travel_history         0
isolation_treatment    0
SARS-CoV-2 Positive    0
dtype: int64